# -*- coding: utf-8 -*-
"""plot_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmwcUKVpTLlzJ-x8_EZBLyP0FJwIStV-
"""





import numpy as np
import matplotlib.pyplot as plt
import math
#finding alphaN
# Extract x and y values from training outputs
x = np.array([4.998747427320433, 5.8986198853150285, 6.675270818604615])
y = np.array([0.2432861460834, math.log10(1.5535), math.log10(1.5329)])

# Fit a linear regression line (y = mx + c)
slope, intercept = np.polyfit(x, y, 1)

print(f"Slope of the best fit line: {slope:.4f}")
alphaN= -slope
print(f"Intercept of the best fit line: {intercept:.4f}")

# Generate y values for the fitted line
y_fit = slope * x + intercept

# Plot the original points and the best-fit line
plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', label='Original points')
plt.plot(x, y_fit, color='red', label=f'Best-fit line (y = {slope:.4f}x + {intercept:.4f})')
plt.xlabel('Log(N)')
plt.ylabel('Log(L)')
plt.title('Best fit Line ')
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Given data
total_dataset_tokens = 1003854
data_budgets_percent = np.array([10, 25, 50, 100])
minimal_validation_losses = np.array([1.7620, 1.6347, 1.5404, 1.5535])

# Calculate dataset tokens used (D)
dataset_tokens_used = (data_budgets_percent / 100) * total_dataset_tokens

# Calculate log L and log D
log_L = np.log(minimal_validation_losses)
log_D = np.log(dataset_tokens_used)

# Fit a linear regression line to log_D and log_L (log_L = m * log_D + c)
slope_log, intercept_log = np.polyfit(log_D, log_L, 1)

# Generate y values for the fitted line
log_L_fit = slope_log * log_D + intercept_log

# Plot log L vs log D with the best-fit line
plt.figure(figsize=(8, 6))
plt.scatter(log_D, log_L, color='purple', label='(log D, log L) points')
plt.plot(log_D, log_L_fit, color='green', label=f'Best-fit line (log L = {slope_log:.4f}log D + {intercept_log:.4f})')
plt.xlabel('log(D)')
plt.ylabel('log( L)')
plt.title('Best fit line')
plt.legend()
plt.grid(True)
plt.show()

# Fit a linear regression line to log_D and log_L (log_L = m * log_D + c)
slope_log, intercept_log = np.polyfit(log_D, log_L, 1)
alphaD= -slope_log
print(f"Slope of the best fit line for (log D, log L): {slope_log:.4f}")
print(f"Intercept of the best fit line for (log D, log L): {intercept_log:.4f}")
print(f"alpha N/ alpha D  = {(alphaN/alphaD):.4f}")





